name: Deploy Service

on:
  workflow_run:
    workflows: ["CI Service"]
    branches: [ main ]
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: StratumTech/Realty-Management-System-Infrastructure/.github/workflows/ssh-deploy.yml@main
    with:
      remote-workdir: /home/stratumtech/Realty-Management-System-Config-Service
      deploy-script: |
        echo "GIT_REPOSITORY_URI=https://github.com/StratumTech/Realty-Management-System-Infrastructure.git" >> .env &&
        docker-compose down &&
        docker-compose pull &&
        docker-compose up -d
    secrets:
      ssh-key-secret: ${{ secrets.SSH_PRIVATE_KEY }}
      ssh-host: ${{ secrets.SERVER_HOST }}
      ssh-user: ${{ secrets.SERVER_USER }}
      config-service-username: ${{ secrets.CONFIG_SERVICE_USERNAME }}
      config-service-password: ${{ secrets.CONFIG_SERVICE_PASSWORD }}
